fix_issues#364
Akegarasu/lora-scripts pull request #395
Opened 2024-03-20 16:16 UTC by neverbiasu

当前,保存的配置文件名为纯数字时间戳,如 `1709263480595.toml`。这种命名方式容易混淆,难以区分不同的配置文件。

为了改善这一点,我对相关代码进行了修改,使保存的配置文件名包含 `output_name` 前缀,格式为 `[output_name]_[timestamp].toml`。例如,如果 `output_name` 为 "model",保存的配置文件名将变为 "model_1709263480595.toml"。

这种命名方式更加直观,便于识别和管理不同的配置文件。

修改详情
- 在 `api.py` 文件中,修改了toml_file的命名,确保下载的配置文件名也包含了 `output_name` 前缀。

修改了 #364

2024-03-21 01:57 UTC, Akegarasu commented
output name may have invalid character for windows path.

2024-03-21 03:24 UTC, neverbiasu commented
I add a clean_filename function to remove the invalid character.🧹

2024-03-26 09:06 UTC, Akegarasu requested changes

2024-03-26 09:06 UTC, Akegarasu commented on mikazuki/app/api.py
> +    filename = clean_filename(output_name)
output might be none

2024-03-26 09:06 UTC, Akegarasu commented on mikazuki/app/api.py
> +        filename = filename.replace(char, '')
crash at here

2024-07-26 15:56 UTC, closed without merging